/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VozovyParkRouteImport } from './routes/vozovy-park'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KarieraRouteImport } from './routes/kariera'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as IndexRouteImport } from './routes/index'

const VozovyParkRoute = VozovyParkRouteImport.update({
  id: '/vozovy-park',
  path: '/vozovy-park',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KarieraRoute = KarieraRouteImport.update({
  id: '/kariera',
  path: '/kariera',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/kariera': typeof KarieraRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sluzby': typeof SluzbyRoute
  '/vozovy-park': typeof VozovyParkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/kariera': typeof KarieraRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sluzby': typeof SluzbyRoute
  '/vozovy-park': typeof VozovyParkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/kariera': typeof KarieraRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sluzby': typeof SluzbyRoute
  '/vozovy-park': typeof VozovyParkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cenik'
    | '/kariera'
    | '/kontakt'
    | '/sitemap.xml'
    | '/sluzby'
    | '/vozovy-park'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cenik'
    | '/kariera'
    | '/kontakt'
    | '/sitemap.xml'
    | '/sluzby'
    | '/vozovy-park'
  id:
    | '__root__'
    | '/'
    | '/cenik'
    | '/kariera'
    | '/kontakt'
    | '/sitemap.xml'
    | '/sluzby'
    | '/vozovy-park'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenikRoute: typeof CenikRoute
  KarieraRoute: typeof KarieraRoute
  KontaktRoute: typeof KontaktRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SluzbyRoute: typeof SluzbyRoute
  VozovyParkRoute: typeof VozovyParkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vozovy-park': {
      id: '/vozovy-park'
      path: '/vozovy-park'
      fullPath: '/vozovy-park'
      preLoaderRoute: typeof VozovyParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kariera': {
      id: '/kariera'
      path: '/kariera'
      fullPath: '/kariera'
      preLoaderRoute: typeof KarieraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenikRoute: CenikRoute,
  KarieraRoute: KarieraRoute,
  KontaktRoute: KontaktRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SluzbyRoute: SluzbyRoute,
  VozovyParkRoute: VozovyParkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
