/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VozovyParkRouteImport } from './routes/vozovy-park'
import { Route as IndexRouteImport } from './routes/index'

const VozovyParkRoute = VozovyParkRouteImport.update({
  id: '/vozovy-park',
  path: '/vozovy-park',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vozovy-park': typeof VozovyParkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vozovy-park': typeof VozovyParkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vozovy-park': typeof VozovyParkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vozovy-park'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vozovy-park'
  id: '__root__' | '/' | '/vozovy-park'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VozovyParkRoute: typeof VozovyParkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vozovy-park': {
      id: '/vozovy-park'
      path: '/vozovy-park'
      fullPath: '/vozovy-park'
      preLoaderRoute: typeof VozovyParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VozovyParkRoute: VozovyParkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
